CONSOLE_ENABLE = no
COMMAND_ENABLE = no
RAW_ENABLE = yes
RGB_MATRIX_CUSTOM_KB = no
COMBO_ENABLE = yes
MOUSEKEY_ENABLE = yes

UNICODE_ENABLE = no
UNICODE_COMMON = yes
UNICODEMAP_ENABLE = yes
LAYER_LOCK_ENABLE = yes
